/* eslint-disable */
/**
 * Generated utilities for implementing server-side Convex query and mutation functions.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * Generated by convex@1.31.2.
 * To regenerate, run `npx convex dev`.
 * @module
 */

import {
    actionGeneric,
    httpActionGeneric,
    queryGeneric,
    mutationGeneric,
    internalActionGeneric,
    internalMutationGeneric,
    internalQueryGeneric,
} from "convex/server";

import type { DataModel } from "./dataModel.js";

/**
 * Define a query in this Convex app's public API.
 */
export const query = queryGeneric as import("convex/server").QueryBuilder<
    DataModel,
    "public"
>;

/**
 * Define a query that is only accessible from other Convex functions (but not from the client).
 */
export const internalQuery = internalQueryGeneric as import("convex/server").QueryBuilder<
    DataModel,
    "internal"
>;

/**
 * Define a mutation in this Convex app's public API.
 */
export const mutation = mutationGeneric as import("convex/server").MutationBuilder<
    DataModel,
    "public"
>;

/**
 * Define a mutation that is only accessible from other Convex functions (but not from the client).
 */
export const internalMutation = internalMutationGeneric as import("convex/server").MutationBuilder<
    DataModel,
    "internal"
>;

/**
 * Define an action in this Convex app's public API.
 */
export const action = actionGeneric as import("convex/server").ActionBuilder<
    DataModel,
    "public"
>;

/**
 * Define an action that is only accessible from other Convex functions (but not from the client).
 */
export const internalAction = internalActionGeneric as import("convex/server").ActionBuilder<
    DataModel,
    "internal"
>;

/**
 * Define an HTTP action.
 */
export const httpAction = httpActionGeneric as import("convex/server").HttpActionBuilder;
